export const StreamData = [
    {
        type: 'Football Match',
        tournament: 'Premier League',
        date: '2023-11-25',
        time: '15:00',
        team1: 'Manchester United',
        team2: 'Liverpool',
    },
    {
        type: 'Cricket Match',
        tournament: 'T20 World Cup',
        date: '2023-11-26',
        time: '18:30',
        team1: 'India',
        team2: 'Australia',
    },
    {
        type: 'Hockey Match',
        tournament: 'FIH Hockey Pro League',
        date: '2023-12-10',
        time: '12:00',
        team1: 'Netherlands',
        team2: 'Germany',
    },
    {
        type: 'Football Match',
        tournament: 'La Liga',
        date: '2023-12-15',
        time: '16:30',
        team1: 'Barcelona',
        team2: 'Real Madrid',
    },
    {
        type: 'Cricket Match',
        tournament: 'Ashes Series',
        date: '2023-12-20',
        time: '03:30',
        team1: 'England',
        team2: 'Australia',
    },
    {
        type: 'Hockey Match',
        tournament: 'Olympic Games',
        date: '2024-01-05',
        time: '09:00',
        team1: 'USA',
        team2: 'Canada',
    },
    {
        type: 'Football Match',
        tournament: 'Bundesliga',
        date: '2024-01-10',
        time: '14:45',
        team1: 'Bayern Munich',
        team2: 'Borussia Dortmund',
    },
    {
        type: 'Cricket Match',
        tournament: 'IPL',
        date: '2024-02-02',
        time: '20:00',
        team1: 'Mumbai Indians',
        team2: 'Chennai Super Kings',
    },
    {
        type: 'Hockey Match',
        tournament: 'Euro Hockey League',
        date: '2024-02-15',
        time: '11:30',
        team1: 'Belgium',
        team2: 'Spain',
    },
    {
        type: 'Football Match',
        tournament: 'UEFA Champions League',
        date: '2024-03-01',
        time: '19:45',
        team1: 'Paris Saint-Germain',
        team2: 'FC Barcelona',
    },
];

